services:
  - type: web
    name: animal-classifier
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: USE_NGROK
        value: "False"
