runtime: python-3.10.13

services:
  - type: web
    name: animal-classifier
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
